print("=== CYBER ARCHIVES - DATA RECOVERY SYSTEM ===")
print("\nAccessing Storage Vault: ancient_fragment.txt")
print("Connection established...")
file = open("ancient_fragment.txt", "r")
content = file.read()
print("\nRECOVERED DATA:")
print(content)
print("\nData recovery complete. Storage unit disconnected.")
file.close()
